language: node_js
node_js:
- stable
services:
- postgresql
- redis-server
before_script:
- psql -c "create database website_messages;" -U postgres
- psql -c "ALTER USER postgres with PASSWORD 'postgres';" -U postgres
- npm install --silent
script:
- cp .env.example .env
- npm run test
- ssh -o StrictHostKeyChecking=no lara@larapollehn.de "cd my-website && git pull &&
  docker-compose up -d --build"
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
