language: node_js
node_js:
- stable
services:
- postgresql
- redis-server
before_script:
- psql -c "create database website_messages;" -U postgres
- psql -c "ALTER USER postgres with PASSWORD 'postgres';" -U postgres
- npm install --silent
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
- chmod 0600 deploy_rsa
script:
- cp .env.example .env
- npm run lint
- npm run test
- eval $(ssh-agent -s)
- ssh-add deploy_rsa
- ssh -o StrictHostKeyChecking=no lara@larapollehn.de "cd my-website && git pull && docker-compose up -d --build"
