version: "3"

# services declaration
services:
  # express service
  website:
    build: .
    restart: always
    ports:
    - 3008:3000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=website_messages
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  # postgresql service
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=website_messages
    volumes:
    - postgres-data:/var/lib/postgresql/data

  # redis service
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

# Volumes declaration
volumes:
  postgres-data:
  redis-data: